CREATE SEQUENCE SKU_NUMBER
START WITH 1 INCREMENT BY 1;

INSERT INTO PRODUCTDIM(
    PRODUCTKEY,
    SKUNUMBER,
    PRODUCTDESCRIPTION,
    BRAND,
    BRANDDESCRIPTION,
    CATEGORYDESCRIPTION
)
SELECT
    ID,
    SKU_NUMBER.NEXTVAL,
    PRODUCTDISPLAYNAME,
    masterCategory,
    subCategory,
    gender
FROM FULL_PRODUCT_INFO;
COMMIT;